name: Build and Push

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GITOPS_REPO: arjansiemons/homelab

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout application repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate version
        id: version
        run: |
          echo "version=$(git rev-list --count HEAD).$(date +%Y%m%d.%H%M)" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Checkout GitOps repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.GITOPS_REPO }}
          token: ${{ secrets.GITOPS_TOKEN }}  # Using GITOPS_TOKEN instead of GITOPS_PAT
          path: gitops

      - name: Update Kustomization
        run: |
          cd gitops/apps/production/health-metrics
          sed -i "s|newTag:.*|newTag: ${{ steps.version.outputs.version }}|" kustomization.yaml
          
      - name: Commit and push GitOps changes
        run: |
          cd gitops
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add apps/production/health-metrics/kustomization.yaml
          git commit -m "Update health-metrics image to ${{ steps.version.outputs.version }}" || echo "No changes to commit"
          git push origin main
